# build.conf
#
# This is a bash script that creates variables related to the build process

# Disable for non-minikube environments. Makes sure the image is saved to the minikube docker daemon
USE_MINIKUBE_DOCKER="y"

# no globbing allowed in the SSHKEY path
SSHKEY="/home/zeph3r/.ssh/github_key_dmaas"

# git related variables
GITREPOSSH="git@github.com:Breeze-Aviation/devops-take-home-test-DavidMaas.git"
GITREPOBRANCH="master"
LOCALWORKINGPATH="/home/zeph3r/projects/"
LOCALGITREPOPATH="/home/zeph3r/projects/devops-take-home-test-DavidMaas"

# Dockerfile related variables
DOCKERFILETEMPLATE="build-template-Dockerfile"
